name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: django.api
          POSTGRES_PASSWORD: django.api
          POSTGRES_DB: postgres
        ports: [ '5432:5432' ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
          architecture: x64

      - name: Criar .env manualmente
        run: |
          echo "POSTGRES_USER=django.api" >> .env
          echo "POSTGRES_PASSWORD=django.api" >> .env
          echo "POSTGRES_DB=postgres" >> .env

      - name: Instalar dependências
        run: |
          pip install poetry
          poetry install

      - name: Rodar flake8
        run: | 
          poetry run flake8