name: CI

on:
  push:
    branches:
      - django.api
  pull_request:
    branches:
      - django.api

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: django.api
          POSTGRES_PASSWORD: django.api
          POSTGRES_DB: postgres
        ports: ['5432:5432']

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          architecture: x64

      - name: Criar arquivo .env
        run: |
          echo "POSTGRES_USER=django.api" >> .env
          echo "POSTGRES_PASSWORD=django.api" >> .env
          echo "POSTGRES_DB=postgres" >> .env

      - name: Instalar dependências com Poetry
        run: |
          pip install poetry
          poetry install

      - name: Rodar flake8 (análise de código)
        run: |
          poetry run flake8
